spring:
    application:
        name: freezone
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/freezone
        username: root
        password: your_password
server:
    port: 8080